os: linux
language: node_js

node_js:
  - 12
  - 11
  - 10
  - 9

cache: npm

script: npm ci

notifications:
  email: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - &test
      stage: test
      script:
        - npm run test:prod
      after_success:
        - npm run travis-deploy-once "npm run report-coverage"

    - &build
      stage: build
      script:
        - npm run build

    - &deploy
      stage: deploy
      node_js: 12
      branches:
        only:
          - master
      script:
        - npm run build
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi
