os: linux
language: node_js
node_js:
  - 11
  - 10
  - 8

cache:
  directories:
    - ~/.npm

notifications:
  email: false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - &test
      stage: test
      script:
        - npm run test:prod
      after_success:
        - npm run travis-deploy-once "npm run report-coverage"

    - &build
      stage: build
      script:
        - npm run build
      cache:
        directories:
          - ~/dist

    - &deploy
      stage: deploy
      node_js: 12
      branches:
        only:
          - master
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
      deploy:
        local_dir: docs
        target_branch: gh-pages
        provider: pages
        cleanup: false
        keep_history: true
        committer_from_gh: true
        token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
        on:
          branch: master
